{{- if .Values.metrics.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ohs.fullname" . }}
  labels:
    {{- include "ohs.labels" . | nindent 4 }}
  {{- with .Values.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    {{- include "ohs.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.keeper.port }}
      targetPort: metrics
      protocol: TCP
{{- end }}
